# Generated by Django 4.2 on 2024-08-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfirmasocio',
            name='firmado_por',
        ),
        migrations.RemoveField(
            model_name='historicalfirmasocio',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsocio',
            name='rol_socio',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='rol_socio',
        ),
        migrations.DeleteModel(
            name='FirmaSocio',
        ),
        migrations.DeleteModel(
            name='HistoricalFirmaSocio',
        ),
    ]
