# Generated by Django 4.2 on 2024-08-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_rolsocio_historicalrolsocio_and_more'),
        ('socios', '0002_remove_historicalfirmasocio_firmado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrolsocio',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='RolSocio',
        ),
        migrations.DeleteModel(
            name='HistoricalRolSocio',
        ),
    ]
