# Generated by Django 4.2 on 2024-08-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='lugar_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.oficina'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoGarantia', to='creditos.tipogarantia'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_segmentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoSegmentacion', to='creditos.tiposegmentacion'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoSolicitud', to='creditos.tiposolicitud'),
        ),
    ]
