# Generated by Django 4.2 on 2024-08-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        ('creditos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociodetallesolicitud',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Socio', to='socios.socio'),
        ),
    ]
